### ISSUE TITLE
Logged into a diffrent map without being invited or able to acess it.

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [AltitudeMapdev/Issues#88] opened 2014-08-21 04:43 UTC
I logged onto the server and was in Electroid's map.  Last time I was on the server I logged off in my world.
![2014-08-20_22 01 36](https://cloud.githubusercontent.com/assets/7586568/3991888/f065360a-28ec-11e4-82af-fc3bb5e4ae09.png)
I also spawned with the equipment, that Electroid probably used.  I was unable to break blocks, and when I teleported to my map and tried to teleport to TourneyCTW, I was not able to.
![2014-08-20_22 01 59](https://cloud.githubusercontent.com/assets/7586568/3991891/043d31dc-28ed-11e4-9f83-8d5560c889de.png)

**Comment by ryanwarsaw** [comment] 2014-08-21 12:19
This is already a known bug and it has already been reported.

**Comment by itsmiiolly** [comment] 2014-08-21 12:35
Dupe of #38

**Closed as completed by itsmiiolly** 2014-08-21 12:35 UTC
Labels: invalid

**Comment by CoWinkKeyDinkInc** [comment] 2014-08-21 17:05
I never had access to the map.  Electroid never added me to the world.

**Comment by itsmiiolly** [comment] 2014-08-21 17:38
Yeah it's a bug with spawning and stuff

**Comment by ryanwarsaw** [comment] 2014-08-21 17:41
@ItsMiiOlly eZ

**Comment by gcflames5** [comment] 2014-08-22 16:21
For some reason the spawning system puts the player in the last world any player was in, its a very wierd system

**Comment by AustinLMayes** [comment] 2014-08-22 18:34
@gcflames5 Can we override this?
