### ISSUE TITLE
Teleporting to Worlds

### ISSUE THREAD

**Issue by BlockDrop74** [AltitudeMapdev/Issues#28] opened 2014-07-15 16:56 UTC
I currently have a problem with teleporting to worlds. Whenever I would type /map BlockDrop74, I would instead get tped to Avaleer's world, Ava1. So, I currently cannot access my own world. It even is the same for using the book to teleport.

**Comment by itsmiiolly** [comment] 2014-07-15 19:02
This has been a known bug for a while and we're not sure what is causing it. I'll have to mess around with unload times and see if that fixes it.

**Comment by hdt80** [comment] 2014-07-17 05:16
Its appears that a restart fixes it.

**Comment by itsmiiolly** [comment] 2014-07-25 10:57
Dupe of #11

**Closed as completed by itsmiiolly** 2014-07-25 10:57 UTC
