### ISSUE TITLE
Joining private world not enforced

### ISSUE THREAD

**Issue by ryanwarsaw** [AltitudeMapdev/Issues#53] opened 2014-08-09 23:05 UTC
Bug Replication:

Join open world that you do not own > have the owner make the world private > and reconnect.

Basically, it spams a shitload of this:

![2014-08-09_18 51 31](https://cloud.githubusercontent.com/assets/6530909/3867974/64a9a12c-2019-11e4-929c-d88180a404a4.png)

Proposed fix:

If a player joins a world that he/she does not have permission to join, teleport them to the hub world.
Possibly a message? "The world you attempted to connect from is Private!".

**Comment by itsmiiolly** [comment] 2014-08-10 11:49
Duplicate of #38

**Closed as completed by itsmiiolly** 2014-08-10 11:49 UTC
